=== Wignesh/coda-training/Day17/books.dtd
<!ELEMENT books (book)+>
<!ELEMENT book (name,author,price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (writter)>
<!ELEMENT writter (first,last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!ATTLIST book bid CDATA #REQUIRED>
<!--
+ - 1 or many
* - 0 or many
? - 0 or 1
  - 1 or 1

#REQUIRED
#IMPLIED
#FIXED "A1"
"A1"
-->

=== Wignesh/coda-training/Day17/books.xml
<!DOCTYPE books SYSTEM "books.dtd">
<books>
    <book bid="1">
        <name>JAVA</name>
        <author>
            <writter>
                <first>
                    James
                </first>
                <last>
                    Bond
                </last>
            </writter>
        </author>
        <price>450</price>
    </book>
    <book bid="2">
        <name>JAVA</name>
        <author>
            <writter>
                <first>
                    James
                </first>
                <last>
                    Bond
                </last>
            </writter>
        </author>
        <price>350</price>
    </book>
</books>
